### ISSUE TITLE
Redirect to home page after logging in + disable saving session

### ISSUE THREAD

**Issue by Garbulix** [anaggh/private-mode#4]
Is that possible to add automatic redirect to **home page** after logging in (not to dashboard)?
I also need to have an ability to disable saving session function, to have confidece that session won't be saved on untrusted computers.

**Comment by anaggh** [comment]
All this plugin does is:
* If user is not logged in, redirect to Login page.

What happens after login is controlled by Bludit Admin Controller -> https://github.com/bludit/bludit/blob/master/bl-kernel/admin/controllers/login.php#L29

You might have to ask for this feature on the main bludit respository -> https://github.com/bludit/bludit/

Feature Request: Redirect to homepage instead of dashboard on successful login
